version: 2
updates:
  - package-ecosystem: "composer"
    target-branch: "11.x"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "05:15"
      timezone: "America/Bogota"
    rebase-strategy: "auto"
