version: "3.8"
services:
    app:
        container_name: database-app
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "8000:8000"
        depends_on:
            - mysql
            - phpmyadmin
            - postgres
            - pgadmin
        volumes:
            - ./:/var/www/html
        networks:
            - lion
    mysql:
        image: mysql
        container_name: database-mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - lion
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: database-phpmyadmin
        links:
            - mysql:mysql
        ports:
            - 8080:80
        environment:
            PMA_HOST: ${DB_HOST}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - lion
    postgres:
        image: postgres
        container_name: database-postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql
        networks:
            - lion
    pgadmin:
        image: dpage/pgadmin4
        container_name: database-pgadmin4
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: ${DB_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - postgres
        networks:
            - lion
volumes:
    mysql_data:
    postgres_data:
networks:
    lion:
