version: "3.8"
services:
    app:
<<<<<<< HEAD
        container_name: lion-database-app
=======
        container_name: lion-sql-app
>>>>>>> 093fd6e303f2ce62bb7b0e175967136476506e30
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        networks:
<<<<<<< HEAD
            - lion_database
    db:
        image: mysql
        container_name: lion-database-mysql
=======
            - lion_sql
    db:
        image: mysql
        container_name: lion-sql-mysql
>>>>>>> 093fd6e303f2ce62bb7b0e175967136476506e30
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
<<<<<<< HEAD
            - lion_database
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: lion-database-phpmyadmin
=======
            - lion_sql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: lion-sql-phpmyadmin
>>>>>>> 093fd6e303f2ce62bb7b0e175967136476506e30
        links:
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
<<<<<<< HEAD
            - lion_database
volumes:
    db_data:
networks:
    lion_database:
=======
            - lion_sql
volumes:
    db_data:
networks:
    lion_sql:
>>>>>>> 093fd6e303f2ce62bb7b0e175967136476506e30
